### ISSUE TITLE
How to get the face.lib?

### ISSUE THREAD

**Issue by yiboin** [willard-yuan/SeetaFaceLib#1]
你好！请教几个简单问题～
1) 我在ubuntu14.04的QT creator(community)上编译的时候提示两个错误：
/home/XXX/SeetaFaceLib/FaceLib/FaceDetection/include/feat/surf_feature_map.h:116: error: ‘memset’ is not a member of ‘std’
/home/XXX/SeetaFaceLib/FaceLib/FaceDetection/srcFD/classifier/surf_mlp.cpp:52: error: ‘memcpy’ is not a member of ‘std’
2) 还有就是我在项目文件下面没有找到下面到face lib，
\# face lib
LIBS += /Users/willard/codes/cpp/face/SeetaFaceLib/FaceLib/FaceIdentification/lib/libviplnet.4.5.dylib

**Comment by willard-yuan** [comment]
@yiboin 第一个问题我这周末在ubuntu下测试一下，有答案了我再这里回复你；第二个libviplnet.4.5.dylib是动态链接库，这个在ubuntu下重新编译[FaceIdentification](https://github.com/willard-yuan/SeetaFaceLib/tree/master/FaceLib/FaceIdentification)才会得到的，你进入到FaceIdentification重新编译一下就ok。

**Comment by shartoo** [comment]
@willard-yuan 您好！请问你的项目用什么编译的？是使用Cmake吗？ 如果有，可够提供一份给我？ shartoo518@gmail.com 谢谢~

**Comment by willard-yuan** [comment]
@shartoo 抱歉，回复晚了，这个项目里面有两个工程，一个是XcodePro/DetectionAlignment，这个是Xcode工程，主要调试和开发的；另外一个是CocsoFace，下面是QT工程，开发的图像界面都在这个工程里。

**Comment by shartoo** [comment]
@willard-yuan 我正在尝试使用CMake编译你的这个项目，会去掉QT图形化界面部分，只写创建图像指纹索引部分和搜索部分。但是在构建过程中，boost无法链接。使用的是 boost 1.6.0 ，看官网说明,boost1.6.0使用时只需要引用头文件即可，但是编译过程不同，通过网上搜索的资料显示boost 1.6.0 引用了`libboost_serialization`等库，所以我没法确认到底哪里出了问题。请问，你使用的是什么版本的boost?
我在 Ubuntu 14.0上编译。多谢~

**Comment by willard-yuan** [comment]
@shartoo 不是boost版本的问题，CMake使用的不熟，平时开发还是用IDE编译。你自己新建一个QT工程，然后把源文件添加进去，在把那个CocsoFace.pro里面的路径修改一下，应该是可以编译过去的。

**Comment by shartoo** [comment]
@willard-yuan  尝试在ubuntu下编译，失败了，好像boost没法用。算了，感谢您的回复~
