### ISSUE TITLE
这个可以拿来做相似图片搜索吗？用到的模型是不是要重新训练？

### ISSUE THREAD

**Issue by txsniper** [willard-yuan/SeetaFaceLib#3]
RT

**Comment by willard-yuan** [comment]
@txsniper 可以用来做相似搜索，模型是需要替换的，因为这个是人脸识别模型。我自己写了个相似图片搜索的qt程序，不过目前只完成了界面展示逻辑，后台检索模型等还在开发中。

**Comment by willard-yuan** [comment]
目前基于相似或相同搜索的界面展示是这样的
![image](https://user-images.githubusercontent.com/5379711/34487694-6bf6b4e0-f010-11e7-9e8f-ee1a1f47468c.png)

如果你有兴趣的话，欢迎加入进来开发这个。
