### ISSUE TITLE
21年用户在Arch上编译成功了...

### ISSUE THREAD

**Issue by muyuuuu** [willard-yuan/SeetaFaceLib#4]
课程大作业要求，正好接了个图像检索的项目，提前练练手，然后搜到了你的博客，看到这个项目感觉挺有意思。

1. 费了九牛二虎之力，在 `Arch` 系统下及 `opencv4.0` 的环境终于编译功过了 `seetaFaceEngine`，`Arch` 下啥都是新的，编译 16 年的老库，很多 bug 真的一言难尽。。。全网搜不到的那种
2. 然后植入局部敏感哈希算法，实现人脸图像的检索，检索时间确实指数量级上升。
3. 然后想说一下，线性搜索那里，可以使用优先级队列，避免排序的开销。

前后rush了两天，大体上成功了，不过没有做出 `qt` 界面可视化结果。

单纯来留个言，哈哈

**Comment by willard-yuan** [comment]
@muyuuuu 恭喜恭喜啊，哈哈
